services:
  requests-handler:
    build: ./requests-handler
    volumes:
      - ./requests-handler:/handler-app  
    ports:
      - "8000:8000"
    depends_on:
      - code-reviewer
    networks:
      - microservices-network

  code-reviewer:
    build: ./code-reviewer
    volumes:
      - ./code-reviewer:/reviewer-app  
    depends_on:
      - redis
    ports:
      - "8001:8001"
    networks:
      - microservices-network
    env_file:
      - ./code-reviewer/core/.env

  celery-worker:
    build: ./code-reviewer
    volumes:
      - ./code-reviewer:/reviewer-app 
    command: celery -A core worker --loglevel=info
    user: "1000:1000"
    depends_on:
      - code-reviewer
      - redis
    env_file:
      - ./code-reviewer/core/.env
    networks:
      - microservices-network

  redis:
    image: redis:7.0-alpine  
    ports:
      - "6380:6379"
    env_file:
      - ./code-reviewer/core/.env
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
